# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:           Alexey Makarin
description:     Assistant Professor in Economics, Einaudi Institute for Economics and Finance (EIEF)


author:
  name:           ''

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/poole/hyde
